import type { Metadata } from "next";
import {  Roboto_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import AuthProvider  from "@/context/AuthProvider";
import { NavBar } from "@/components/NavBar";
import { WavyBackground } from "@/components/ui/wavy-background";


const inter = Roboto_Mono({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default  function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} dark`}>
        <AuthProvider>
        <WavyBackground   waveOpacity={0.8} waveWidth={70} colors={[`#2F6690`,`#3A7CA5`, `#D9DCD6`,`#16425B`,`#81C3D7`]} >
        <NavBar/>
        {children}
        </WavyBackground>
        <Toaster richColors={true}
        closeButton={true}
         />
        </AuthProvider>
      </body>
    </html>
  );
}
